# Generated by Django 3.0.8 on 2021-02-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100)),
                ('train_number', models.CharField(max_length=225)),
                ('rows_available', models.IntegerField()),
                ('available_seats', models.CharField(max_length=225, null=True)),
                ('window_seats', models.CharField(max_length=225, null=True)),
                ('seat_agent', models.CharField(max_length=225, null=True)),
                ('booked_seats', models.CharField(max_length=225, null=True)),
                ('middle_seats', models.CharField(max_length=250, null=True)),
                ('aisle_seats', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('seat_number', models.IntegerField()),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booker')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Train')),
            ],
        ),
    ]
